[package]
name = "echo-client"
version = "0.1.0"
authors = ["kteza1 <k.teza1@gmail.com>"]

[dependencies]
tokio-core = "0.1"
tokio-io = "0.1"
futures = "0.1"
bytes = "0.4"
quick-error = "1.1"
tokio-timer = "0.1"
